### ISSUE TITLE
The new .pem file can be used to update the device

### ISSUE THREAD

**Issue by Hoang-Anh-Duong** [atmark-techno/mkswu#1]
Hello team!
I'm a developer. Now I am using your source. So I was stuck when using the new .pem file.
My step:
+ Gen key ($ sh genkey.sh)
![image](https://user-images.githubusercontent.com/87181496/234449138-16d53667-c78f-410d-9878-cad4204ecbf8.png)
+ Update file config mkswu.conf
![image](https://user-images.githubusercontent.com/87181496/234449258-861cca04-f528-4079-a100-aa351e7c05c3.png)
![image](https://user-images.githubusercontent.com/87181496/234449300-f73a7794-310d-43b2-8659-a2600ce1dd30.png)
+ Create .swu file ($ mkswu --init)
+ Create .desc and add to image .swu
+ Add file .pem to the device needs update
+ Run update .swu image with device needs update
![image](https://user-images.githubusercontent.com/87181496/234449588-d77fa3b1-9d2c-4698-a9e7-fc6645951243.png)
Please show me if I'm wrong somewhere, thanks !

**Comment by martinetd** [comment]
Hello,

looking at your configuration you've generated two key pairs already, which one are you trying to use?

The normal workflow is as follow; for your first key:
* `mkswu --init` will generate a new key (including running genkey.sh for you; that script is only still around as compatibility for our older manual and we'll probably remove it in a few more months) as well as "initial_setup.swu" (and its source desc file)
* Install initial_setup.swu on a new board: the initial setup uses an "open key" that allows anyone to install the first update after shipping, just as the initial root password is blank. This initial setup locks the device so other "open" updates cannot be installed and root password becomes set.
* After having installed the initial setup, you should be able to install other updates you've generated yourself.

For your second key:
* Running mkswu --genkey (or genkey.sh) and following the prompt to create another key will generate a new key pair and fill in your config to append the new certificate to your device the next time you install an update (appending to PUBKEY, setting UPDATE_CERTS in the config)
* Generate and install any new swu; this will still be using the old PRIVKEY as the new one isn't trusted yet!
* After you've installed this swu, /etc/swupdate.pem on the device will allow both the new and the old key pairs.
At this point you can update your config: change PUBKEY to not include the old PUBKEY, and uncomment PRIVKEY. In your screenshot you still have the old PUBKEY set, so it's signing the update against the wrong certificate.
* Once you install another swu with these settings, the old certificate (PUBKEY) will be removed from the device's allow list.
At this point you can remove UPDATE_CERTS if you want (but it doesn't really hurt either way)


https://github.com/atmark-techno/mkswu/blob/master/docs/common_errors.md#signature-verification-failed--sign_fail has a bit of background on how to reset your device certificates if required; you can manually update /etc/swupdate.pem on your device just fine as well but it's important than the PRIVKEY you use matches the first PUBKEY of the list as we have no way of checking they're coherent (I'll try to check if there isn't an openssl command that could verify this to catch things kind of configuration error, but I think there isn't)

Does that help?

**Comment by martinetd** [comment]
> I'll try to check if there isn't an openssl command that could verify this to catch things kind of configuration error, but I think there isn't

hmm, the certificate actually does contain the public key (`openssl x509 -in <cert> -noout  -pubkey`) which can also be derived from the key (`openssl ec -in <key> -pubout`), but getting this info from the private key requires entering the password a second time so it's a bit too annoying to do regularly.

I might want to add a `--confcheck` option or similar that prompts for this kind of verifications in the future, but I'm leaving this open for now; it's a bit of a trick problem.

**Comment by Hoang-Anh-Duong** [comment]
> https://github.com/atmark-techno/mkswu/blob/master/docs/common_errors.md#signature-verification-failed--sign_fail has a bit of background on how to reset your device certificates if required; you can manually update /etc/swupdate.pem on your device just fine as well but it's important than the PRIVKEY you use matches the first PUBKEY of the list as we have no way of checking they're coherent (I'll try to check if there isn't an openssl command that could verify this to catch things kind of configuration error, but I think there isn't)

After ur suggestions, I finally did it, much appreciated !
